# Generated by Django 4.0.3 on 2022-05-14 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.TextField(max_length=500)),
                ('slug', models.CharField(max_length=200)),
                ('category_id', models.BigIntegerField(null=True)),
                ('post_image', models.FileField(upload_to='images/post/')),
                ('user_id', models.BigIntegerField(null=True)),
                ('post_status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 14, 10, 46, 10, 747864))),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dhurbaapp_blogposts',
            },
        ),
    ]
