# Generated by Django 4.0.3 on 2022-05-14 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 10, 47, 14, 55528)),
        ),
    ]
